### ISSUE TITLE
Any idea for android 8+ ?

### ISSUE THREAD

**Issue by TayfunCesur** [abhinavsuthar/Android_Spy_App#4]

**Comment by abhinavsuthar** [comment]
@TayfunCesur Please describe your question.
BTW this app works in android 8+

**Comment by TayfunCesur** [comment]
I thought your app is working on background and hidden from user. That is why I ask for android 8+. Because there are so many restrictions on android 8. You said this app works android 8 on **foreground** ?

**Comment by abhinavsuthar** [comment]
You can use some features in background on android 8+ but on some devices it will show notification that this app is using camera in background (for eg). But you can avoid that by making a transparent activity and start camera2 api instance from activity itself and then close the activity. On most of the devices user will not notice it. Because process is much faster.
