### ISSUE TITLE
Is it possible to read WhatsApp message !

### ISSUE THREAD

**Issue by jish-44** [abhinavsuthar/Android_Spy_App#5]

**Comment by abhinavsuthar** [comment]
Yeah, because some apps do read WhatsApp message. I know some methods but they are not much reliable:
1. Read the whole screen using accessibility service as Google Talkback do. Using accessibility service you will know that which app is in foreground right now, then you have to process data.
2. 1st option can also be done by OCR( optical character reader). You have to detect when WhatsApp is in foreground then take a screenshot and convert it to text using google play services OCR.
3. Read all the notifications. But it will give you only incoming messages.

Personally, I didn't like any of these methods. There should be something else.

**Comment by Toqeer12** [comment]
any link or source code related this
